# Generated by Django 4.2.26 on 2025-11-21 17:29

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='EmpresaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='quicksolutions.categoria')),
            ],
            options={
                'db_table': 'empresa_categoria',
            },
        ),
        migrations.CreateModel(
            name='EmpresaExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cuil', models.BigIntegerField()),
                ('telefono', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=50)),
                ('categorias', models.ManyToManyField(through='quicksolutions.EmpresaCategoria', to='quicksolutions.categoria')),
            ],
            options={
                'db_table': 'empresa_externa',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.categoria')),
            ],
            options={
                'db_table': 'producto',
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'provincia',
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicioEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'solicitud_servicio_estado',
            },
        ),
        migrations.CreateModel(
            name='TipoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipo_servicio',
            },
        ),
        migrations.CreateModel(
            name='Perfiles',
            fields=[
                ('id', models.OneToOneField(db_column='id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_de_nacimiento', models.DateField(blank=True, null=True)),
                ('rol', models.CharField(choices=[('cliente', 'Cliente'), ('empleado', 'Empleado'), ('admin', 'Admin')], default='cliente', max_length=50)),
            ],
            options={
                'db_table': 'perfiles',
            },
        ),
        migrations.CreateModel(
            name='TipoMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.producto')),
            ],
            options={
                'db_table': 'tipo_mantenimiento',
            },
        ),
        migrations.CreateModel(
            name='SolicitudServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada', models.DateTimeField(blank=True, null=True)),
                ('monto', models.FloatField(blank=True, null=True)),
                ('tercearizado', models.BooleanField()),
                ('con_logistica', models.BooleanField()),
                ('fecha_iniciada', models.DateTimeField(blank=True, null=True)),
                ('fecha_revisada', models.DateTimeField(blank=True, null=True)),
                ('fecha_presupuestada', models.DateTimeField(blank=True, null=True)),
                ('diagnostico_tecnico', models.TextField(blank=True, null=True)),
                ('fecha_aprobada', models.DateTimeField(blank=True, null=True)),
                ('fecha_finalizada', models.DateTimeField(blank=True, null=True)),
                ('fecha_cancelada', models.DateTimeField(blank=True, null=True)),
                ('resumen', models.TextField(blank=True, null=True)),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.producto')),
                ('id_solicitante', models.ForeignKey(db_column='id_solicitante', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_creadas', to=settings.AUTH_USER_MODEL)),
                ('id_solicitud_servicio_estado', models.ForeignKey(db_column='id_solicitud_servicio_estado', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.solicitudservicioestado')),
                ('id_tecnico_asignado', models.ForeignKey(blank=True, db_column='id_tecnico_asignado', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_asignadas', to=settings.AUTH_USER_MODEL)),
                ('id_tipo_mantenimiento', models.ForeignKey(blank=True, db_column='id_tipo_mantenimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='quicksolutions.tipomantenimiento')),
                ('id_tipo_servicio', models.ForeignKey(db_column='id_tipo_servicio', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.tiposervicio')),
            ],
            options={
                'db_table': 'solicitud_servicio',
            },
        ),
        migrations.CreateModel(
            name='ReparacionExterna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_solicitud_externa', models.IntegerField()),
                ('id_empresa', models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.empresaexterna')),
                ('id_solicitud', models.ForeignKey(db_column='id_solicitud', on_delete=django.db.models.deletion.CASCADE, to='quicksolutions.solicitudservicio')),
            ],
            options={
                'db_table': 'reparacion_externa',
            },
        ),
        migrations.CreateModel(
            name='Localidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('id_provincia', models.ForeignKey(db_column='id_provincia', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.provincia')),
            ],
            options={
                'db_table': 'localidad',
            },
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('piso', models.IntegerField(blank=True, null=True)),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('nro_seguimiento', models.IntegerField(blank=True, null=True)),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.localidad')),
                ('id_solicitud_servicio', models.OneToOneField(db_column='id_solicitud_servicio', on_delete=django.db.models.deletion.CASCADE, to='quicksolutions.solicitudservicio')),
            ],
            options={
                'db_table': 'envio',
            },
        ),
        migrations.AddField(
            model_name='empresacategoria',
            name='id_empresa',
            field=models.ForeignKey(db_column='id_empresa', on_delete=django.db.models.deletion.CASCADE, to='quicksolutions.empresaexterna'),
        ),
        migrations.CreateModel(
            name='Domicilio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=50)),
                ('numero', models.IntegerField()),
                ('departamento', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=50)),
                ('id_localidad', models.ForeignKey(db_column='id_localidad', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.localidad')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'domicilio',
            },
        ),
        migrations.CreateModel(
            name='ChecklistMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarea', models.CharField(max_length=150)),
                ('obligatorio', models.BooleanField()),
                ('id_tipo_mantenimiento', models.ForeignKey(db_column='id_tipo_mantenimiento', on_delete=django.db.models.deletion.PROTECT, to='quicksolutions.tipomantenimiento')),
            ],
            options={
                'db_table': 'checklist_mantenimiento',
            },
        ),
    ]
