# Generated by Django 4.2.26 on 2025-11-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicksolutions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='pais',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='piso',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
