# Generated by Django 4.2.26 on 2025-11-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicksolutions', '0002_remove_domicilio_pais_domicilio_piso'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudservicio',
            name='tercearizado',
        ),
    ]
