# Generated by Django 4.2.26 on 2025-11-26 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quicksolutions', '0003_remove_solicitudservicio_tercearizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipomantenimiento',
            name='id_producto',
        ),
    ]
