# Generated by Django 4.2.26 on 2025-11-27 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quicksolutions', '0004_remove_tipomantenimiento_id_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checklistmantenimiento',
            name='id_tipo_mantenimiento',
            field=models.ForeignKey(db_column='id_tipo_mantenimiento', on_delete=django.db.models.deletion.CASCADE, to='quicksolutions.tipomantenimiento'),
        ),
    ]
